from robo_ai.exception.api_error import ApiError


class NotFoundError(ApiError):
    pass
